
# supabase/config.toml

# Configuraci贸n para la funci贸n 'chat'
[functions.chat]
  import_map = "./import_map.json"

# Configuraci贸n para la funci贸n 'process-csv'
[functions.process-csv]
  import_map = "./import_map.json"
